### ISSUE TITLE
Clarification on ‘program’ Field Format in RobustFill Dataset

### ISSUE THREAD

**Issue by TnTWoW** [google-deepmind/exedec#1]
Hi Kensen,

Great work! I want to know why the 'program' field in the RobustFill dataset is not a program string that conforms to DSL syntax as I understood it, but rather a numeric string. Is there something wrong?"

<img width="464" alt="robustfill" src="https://github.com/user-attachments/assets/b349083d-658b-49ce-b6d9-ee02ae894707">

Thanks for your attention!

**Comment by kensens** [comment]
Yes this is expected for RobustFill. The numbers correspond to indices into the vocabulary table. Please use `dsl.decode_program` to parse this into a RobustFill program object: https://github.com/google-deepmind/exedec/blob/main/tasks/robust_fill/dsl.py#L671.

You can see an example of this usage here https://github.com/google-deepmind/exedec/blob/main/data/data_utils.py#L312, or just use `data_utils.ids_to_program` and `data_utils.run_program` directly. See `data_utils_test.py` for more examples of using those.

**Comment by TnTWoW** [comment]
Thank you! I got it.
